## AIF_sprint13_cnn2
この課題の目的  
・スクラッチを通してCNNの基礎を理解する   
・基本的なCNNのキーワードを学習する   
・初期の有名なCNNモデルを知る   

【目的としないこと】   
実用的なCNNモデルに関する知識の習得

In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_mldata

mnist_dir = "/Users/andoutakaaki/DIC_study/sprint9/mnist_data/"

# MNISTの読み込み
mnist = fetch_mldata('MNIST original', data_home=mnist_dir)

# trainとtestに分割
# MNISTの読み込み
X_train, X_test, y_train, y_test = train_test_split(mnist.data, mnist.target, test_size=0.2)
# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

# ラベルをint型にしておく
y_train = y_train.astype(np.int)
y_test = y_test.astype(np.int)
y_val = y_val.astype(np.int)

X_train = X_train.astype(np.float)
X_test = X_test.astype(np.float)
X_val = X_val.astype(np.float)
X_train /= 255
X_test /= 255
X_val /= 255

from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train[:, np.newaxis])
y_test_one_hot = enc.transform(y_test[:, np.newaxis])
y_val_one_hot = enc.transform(y_val[:, np.newaxis])

X_train = X_train.reshape(44800,1, 28,28)
X_test = X_test.reshape(14000,1, 28,28)
X_val = X_val.reshape(11200,1, 28,28)


print(X_train.shape,X_test.shape,X_val.shape)
print(y_train_one_hot,y_test_one_hot.shape,y_val_one_hot)

(44800, 1, 28, 28) (14000, 1, 28, 28) (11200, 1, 28, 28)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]] (14000, 10) [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [24]:
# チャンネル数を1に限定した2次元畳み込み層のクラス
class SimpleConv2d:
    
    
    def __init__(self, w, b, pad, stride):
        
        self.Out = None
        seif.x = None
        self.w = w
        self.b = b
        self.P = pad
        self.S = stride
        self.dx = None
        self.dw = None
        self.db= None
    
    # forward
    def forward(self, x):
        self.x = x
        N, C, H, W = x.shape
        F, C, FH, FW = self.w.shape
        H_out = 1 + (H + 2*self.P - FH) / self.S
        W_out = 1 + (W + 2*self.P - FW) / self.S
        self.Out = np.zeros((N, F, H_out, W_out))
        x_pad = np.pad(x, ((0, 0),(0, 0),(self.P,self.P),(self.P,self.P)), "constant",constant_values=0)
        for n in N:
            for f in F:
                for i in (0, H, S):
                    for j in (0, W, S):
                        Out[n, f, int(i / self.S), int(j / self.S)] = np.sum(X_pad[n, :, i : i+FH, j : j+FW] * self.w[f, :, :, :]) + self.b[f]
                            
    # backward
    def backward(self, dout):
        N, C, H, W = self.x.shape
        F, C, FH, FW = self.w.shape
        N, F, H_out, W_out = dout.shape
        x_pad = np.pad(x, ((0, 0),(0, 0),(self.P,self.P),(self.P,self.P)), "constant",constant_values=0)
        self.dx = np.zeros(x_pad.shape)
        self.dw = np.zeros(w.shape)
        self.db = np.zeros(b.shape)
        for n in N:
            for f in F:
                for i in(O, H, S):
                    for j in(O, W, S):
                        dx[n, :, i : i+FH, j : j+FW] += dout[n, f, int(i / S), int(j / S)]  * w[f, : , : , ]
                        
  