## AIF_sprint22_rnn_scratch
1.この課題の目的   
スクラッチを通してRNNの基礎を理解する    

【目的としないこと】   
実用的なRNNモデルに関する知識の習得   

手法の説明を記述する。（2日目夜発表）   

2.進め方    
SimpleRNNをスクラッチで実装する。（1日目〜2日目）    
sprint23はRNNの発展であるLSTMを扱う。LSTMもRNNの一種であるため、今回扱う基礎的なRNNはSimpleRNNと呼び分けることにする。    

3.スクラッチによる実装   
NumPyなど最低限のライブラリのみを使いアルゴリズムを実装していく。TensorFlowなどは使用しない。       
これまでのsprintで作成したニューラルネットワークを拡張する形で作成する。


In [1]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [2]:
import numpy as np
# from common.layers import *
# from common.functions import sigmoid

### 小さな配列での実験

In [47]:
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h_s = np.zeros((batch_size, n_sequences, n_nodes))
b = np.array([1])



In [48]:
a_t = np.dot(x[:, 0, :], w_x) 
a_t

array([[0.0007, 0.0013, 0.0019, 0.0023]])

In [49]:
h_s[:, 0, :] =  np.tanh(a_t + b)

In [50]:
h_s[:, 0, :]

array([[0.76188798, 0.76213958, 0.76239095, 0.76255841]])

In [51]:
a_h = np.dot(h_s[:, 0, :], w_h)
a_h

array([[0.07623574, 0.13721527, 0.19819481, 0.25155044]])

In [53]:
a_t1 = np.dot(x[:, 1, :], w_x)
a_t1

array([[0.0011, 0.0021, 0.0031, 0.0038]])

In [54]:
h_s[:, 1, :] = np.tanh(a_h + a_t1 + b)

In [55]:
h_s[:, 1, :]

array([[0.792209  , 0.8141834 , 0.83404912, 0.84977719]])

In [57]:
a_h1 = np.dot(h_s[:, 1, :],w_h)
a_h1

array([[0.08321832, 0.14902269, 0.21482707, 0.27229095]])

In [59]:
a_t2 = np.dot(x[:, 2, :], w_x)
a_t2

array([[0.0015, 0.0029, 0.0043, 0.0053]])

In [60]:
h_s[:, 2, :] = np.tanh(a_h1 + a_t2 + b)

In [61]:
h_s[:, 2, :]

array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]])

In [62]:
h_s

array([[[0.76188798, 0.76213958, 0.76239095, 0.76255841],
        [0.792209  , 0.8141834 , 0.83404912, 0.84977719],
        [0.79494228, 0.81839002, 0.83939649, 0.85584174]]])

In [89]:
class SimpleRNN:
    def __init__(self, w_x, w_h, b):
        self.params = [w_x, w_h, b]
        self.grads = [np.zeros_like(w_x), np.zeros_like(w_h), np.zeros_like(b)]
        self.cache = None
        
    def forward(self, x, h_s0):
        w_x, w_h, b = self.params
        t = np.dot(h_s0, w_h) + np.dot(x, w_x) + b
        h_s = np.tanh(t)
        
        self.cache = (x, h_s0, h_s)
        
#         x, h_prev, h_next = self.cache
#         batch_size, n_sequences, n_features = x.shape
#         n_features, n_nodes = w_x.shape

#         h_s[:, 0, :] = np.tanh(np.dot(x[:, 0, :], w_x) + b)
#         h_s[:, 1, :] = np.tanh(np.dot(h_s[:, 0, :], w_h) + np.dot(x[:, 1, :], w_x) + b)
#         h_s[:, 2, :] = np.tanh(np.dot(h_s[:, 1, :], w_h) + np.dot(x[:, 2, :], w_x) + b)
        
        return h_s

#         self.layers = []
#         h_s = np.empty((batch_size, n_sequences, n_nodes), dtype='f')

#         if not self.stateful or self.h is None:
#             self.h = np.zeros((batch_size, n_nodes), dtype='f')

#         for t in range(n_sequences):
#             layer = RNN(*self.params)
#             self.h = layer.forward(xs[:, t, :], self.h)
#             h_s[:, t, :] = self.h
#             self.layers.append(layer)


# def backward(self, dh_next):
#         Wx, Wh, b = self.params
#         x, h_prev, h_next = self.cache
        
#         dt = dh_next * (1 - h_next **  2)
#         db = np.sum(dt, axis = 0)
#         dWh = np.dot(h_prev.T, dt)
#         dWx = np.dot(x.T, dt)
#         dx = np.dot(dt, Wx.T)
        
#         self.grads[0][...]= dWx
#         self.grads[1][...]= dWh
#         self.grads[2][...]= db
        
#         return dx, dh_prev


In [90]:
h_s

array([[[0.76188798, 0.76213958, 0.76239095, 0.76255841],
        [0.792209  , 0.8141834 , 0.83404912, 0.84977719],
        [0.79494228, 0.81839002, 0.83939649, 0.85584174]]])

In [7]:
# rnn = RNN(w_x, w_h, b)

In [8]:
# rnn.forward(x, h)

In [9]:
# rnn.forward([1, 2], h)

In [28]:
/

#     def backward(self, dh_s):
#         w_x, w_h, b = self.params
#         batch_size, n_sequences, n_nodes = dh_s.shape
#         n_features, n_nodes = w_x.shape

#         dxs = np.empty((batch_size, n_sequences, n_features), dtype='f')
#         dh = 0
#         grads = [0, 0, 0]
#         for t in reversed(range(n_sequences)):
#             layer = self.layers[t]
#             dx, dh = layer.backward(dh_s[:, t, :] + dh)
#             dxs[:, t, :] = dx

#             for i, grad in enumerate(layer.grads):
#                 grads[i] += grad

#         for i, grad in enumerate(grads):
#             self.grads[i][...] = grad
#         self.dh = dh

#         return dxs

#     def set_state(self, h):
#         self.h = h

#     def reset_state(self):
#         self.h = None

## Kerasコード¶

In [10]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Input, Dense, Embedding
from keras.models import Model
from keras.layers import SimpleRNN
from keras.datasets import imdb

max_features = 10000
maxlen = 40
batch_size = 32

print('load dataset')
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

print('padding')
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)

print('build model')
inp = Input(shape=(maxlen,), dtype='int32', name='main_input')
x = Embedding(max_features, 128)(inp)
simple_rnn_out = SimpleRNN(32)(x)
predictions = Dense(1, activation='sigmoid')(simple_rnn_out)
model = Model(inputs=inp, outputs=predictions)

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('train')
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=3,
          validation_data=(x_test, y_test))
score, acc = model.evaluate(x_test, y_test,
                            batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)

Using TensorFlow backend.


load dataset
padding
build model
train
Train on 25000 samples, validate on 25000 samples
Epoch 1/3
25000/25000 [==============================] - 31s 1ms/step - loss: 0.5119 - acc: 0.7413 - val_loss: 0.4447 - val_acc: 0.7942

### Modelの構成¶

In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
main_input (InputLayer)      (None, 40)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 40, 128)           1280000   
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 32)                5152      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 1,285,185
Trainable params: 1,285,185
Non-trainable params: 0
_________________________________________________________________


### どんなデータ？

In [12]:
print(x_train[0:10],x_train[0:10].shape)
print(y_train[0:10])

[[  22   21  134  476   26  480    5  144   30 5535   18   51   36   28
   224   92   25  104    4  226   65   16   38 1334   88   12   16  283
     5   16 4472  113  103   32   15   16 5345   19  178   32]
 [ 152  491   18    2   32 7464 1212   14    9    6  371   78   22  625
    64 1382    9    8  168  145   23    4 1690   15   16    4 1355    5
    28    6   52  154  462   33   89   78  285   16  145   95]
 [  23   22   12  272   40   57   31   11    4   22   47    6 2307   51
     9  170   23  595  116  595 1352   13  191   79  638   89    2   14
     9    8  106  607  624   35  534    6  227    7  129  113]
 [  14   31    9  242  955   48   25  279    2   23   12 1685  195   25
   238   60  796    2    4  671    7 2804    5    4  559  154  888    7
   726   50   26   49 7008   15  566   30  579   21   64 2574]
 [  74  233  334  207  126  224   12  562  298 2167 1272    7 2601    5
   516  988   43    8   79  120   15  595   13  784   25 3171   18  165
   170  143   19   14    5 7

### どんな結果？

In [13]:
pred = model.predict(x_train)
print(pred[0:10],pred[0:10].shape)

[[0.99606067]
 [0.01465181]
 [0.00525351]
 [0.98470473]
 [0.04369648]
 [0.00405202]
 [0.691591  ]
 [0.00213527]
 [0.99164855]
 [0.00812553]] (10, 1)


In [14]:
y_train[0:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

### 今日のデータ

In [15]:
import numpy as np
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h = np.zeros((batch_size, n_nodes))
b = np.array([1])

In [16]:
print(x)
print('=====')
print(w_x)
print('=====')
print(w_h)

[[[0.01 0.02]
  [0.02 0.03]
  [0.03 0.04]]]
=====
[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
=====
[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]


## Word2vec

### 前処理

In [78]:
import numpy as np
import sys
sys.path.append('..')

def preprocess(text):
    text = text.lower()
    text = text.replace('.', ' .')
    words = text.split(' ')

    word_to_id = {}
    id_to_word = {}
    for word in words:
        if word not in word_to_id:
            new_id = len(word_to_id)
            word_to_id[word] = new_id
            id_to_word[new_id] = word

    corpus = np.array([word_to_id[w] for w in words])

    return corpus, word_to_id, id_to_word

#text = 'You say goodbye and I say hello.'
text = 'I love Tom and I love Mike.'
corpus , word_to_id, id_to_word = preprocess(text)
print(corpus)

[0 1 2 3 0 1 4 5]


### Context & Target

In [79]:
def create_contexts_target(corpus, window_size=1):
    '''one-hot表現への変換を行う
    :param words: 単語IDのNumPy配列
    :param vocab_size: 語彙数
    :return: one-hot表現に変換後のNumPy配列
    '''
    target = corpus[window_size:-window_size]
    contexts = []

    for idx in range(window_size, len(corpus)-window_size):
        cs = []
        for t in range(-window_size, window_size + 1):
            if t == 0:
                continue
            cs.append(corpus[idx + t])
        contexts.append(cs)

    return np.array(contexts), np.array(target)

context, target = create_contexts_target(corpus, window_size=1)
context, target

(array([[0, 2],
        [1, 3],
        [2, 0],
        [3, 1],
        [0, 4],
        [1, 5]]), array([1, 2, 3, 0, 1, 4]))

### One-hotベクトル化

In [80]:
def convert_one_hot(corpus, vocab_size):
    '''one-hot表現への変換
    :param corpus: 単語IDのリスト（1次元もしくは2次元のNumPy配列）
    :param vocab_size: 語彙数
    :return: one-hot表現（2次元もしくは3次元のNumPy配列）
    '''
    N = corpus.shape[0]

    if corpus.ndim == 1:
        one_hot = np.zeros((N, vocab_size), dtype=np.int32)
        for idx, word_id in enumerate(corpus):
            one_hot[idx, word_id] = 1

    elif corpus.ndim == 2:
        C = corpus.shape[1]
        one_hot = np.zeros((N, C, vocab_size), dtype=np.int32)
        for idx_0, word_ids in enumerate(corpus):
            for idx_1, word_id in enumerate(word_ids):
                one_hot[idx_0, idx_1, word_id] = 1

    return one_hot

In [81]:
vocab_size= len(word_to_id)
context_one_hot = convert_one_hot(context, vocab_size)
context_one_hot

array([[[1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0]],

       [[0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0]],

       [[0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0]],

       [[1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]],

       [[0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1]]], dtype=int32)

In [82]:
convert_one_hot(target, vocab_size)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]], dtype=int32)

## 説明課題

### RNNが通常の全結合層ニューラルネットワークと異なるのはどういった点か
全結合層ニューラルネットワークは、中間層がすべて全結合層となっている。一方で、RNNは、中間層が自己フィードバックができる隠れ層となっている点が異なる。例えば、前時刻の層の出力を考慮して現中間層の出力を計算したり、次時刻の層の出力を考慮して現中間層へと両方向に情報をフィードバックしたりさせられる。3層が一般的だが、系列的に中間層のフィードバックを記憶できるため、系列データへの対応が可能である。

### なぜRNNは自然言語処理に使われるのか
RNNは前後の時系列情報を考慮して識別することができる。自然言語処理の代表的なタスクとして言語予測があるが、例えば「今日は良い天気です」という文章において、「今日は」「良い」という時系列データを与えると、次に現れる単語として「天気」を予測するタスクである。RNNを利用することで、過去の系列情報から文脈の流れを考慮した予測ができるようになる。

### SimpleRNNは勾配消失が起きやすいと言われているがそれはなぜか
RNNは、系列データの文脈を捉えて推定を行うことができる。この時、系列データの文脈全体を反映させることが重要であり、時刻tから離れた遠い過去の時刻のデータを時刻tの出力に反映しなければならない。しかし、RNNを時間方向に展開すると深いニューラルネットワークとみなすことができ、誤差逆伝播時に誤差が入力に近い階層まで伝播させることが困難になる。したがって、特に系列データが長い場合、SimpleRNNでは勾配消失が起きやすくなる。一般的には、SimpleRNNは１０時刻程度（すなわち１０単語）程度のデータが限界となることが多い。